name: Check Julia Python Consistency

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1.10'

    - name: Install Julia packages
      run: |
        julia -e '
          using Pkg;
          try
              Pkg.instantiate();
              Pkg.add(["Colors", "DelimitedFiles", "FileIO", "JLD", "PyPlot"]);
          catch err
              println("Error installing Julia packages: $err")
              exit(1)
          end'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib juliacall || { echo "Error installing Python packages"; exit 1; }

    - name: Run Python script
      run: |
        python test_consistency.py || { echo "Error running Python script"; exit 1; }
        